import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import ts from 'typescript';import {createHash} from 'node:crypto';
import {isCrewCheerType} from '../lib/crew-cheers.ts';import {publicSeasonEvent} from '../lib/season-schedule-contract.ts';
const source=readFileSync(new URL('../app/api/crew-cheers/route.ts',import.meta.url),'utf8');
const js=ts.transpileModule(source.replace(/^import[\s\S]*?;\n/gm,''),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
function harness(authenticated=false){let day='2026-09-15';const files=new Map();const visitor='11111111-1111-4111-8111-111111111111';const store={async upload(path,body){if(files.has(path))return{error:{statusCode:'409',message:'duplicate'}};files.set(path,body);return{}},async download(path){return files.has(path)?{data:{text:async()=>files.get(path)}}:{error:{statusCode:'404',message:'not found'}}}};
const deps={createHash,randomUUID:()=>visitor,NextResponse:{json:(body,options)=>({body,...options,cookies:{set(){}}})},createClient:async()=>({auth:{getClaims:async()=>({data:{claims:authenticated?{sub:'member'}:null}})}}),getServiceClient:()=>({}),privateUploadStore:async()=>store,certificationDay:()=>day,isCrewCheerType,guardMutationRequest:()=>null,guardReadRequest:()=>null,readLimitedJson:async req=>({ok:true,value:req.body})};const exports={};new Function('exports',...Object.keys(deps),js)(exports,...Object.values(deps));return{...exports,files,nextDay:()=>day='2026-09-16',req:(type='heart')=>({cookies:{get:()=>({value:visitor})},body:{type}})}}
test('참관객은 4가지 이모지를 선택할 수 있고 그 외 값은 거절',async()=>{for(const type of ['heart','clap','smile','run']){const h=harness();assert.equal((await h.POST(h.req(type))).body.reaction,type)}const h=harness();assert.equal((await h.POST(h.req('invalid'))).status,400);assert.equal(h.files.size,0)});
test('동시 클릭과 다른 이모지 재시도도 하루 한 번만 저장하며 다음날 재개',async()=>{const h=harness();await Promise.all([h.POST(h.req('heart')),h.POST(h.req('run'))]);assert.equal(h.files.size,1);assert.equal((await h.GET(h.req())).body.reaction,'heart');h.nextDay();assert.equal((await h.GET(h.req())).body.sent,false);await h.POST(h.req('smile'));assert.equal(h.files.size,2)});
test('로그인한 멤버에게 응원을 숨기고 직접 요청도 거절',async()=>{const h=harness(true);assert.equal((await h.GET(h.req())).body.visible,false);assert.equal((await h.POST(h.req())).status,403);assert.equal(h.files.size,0)});
test('공개 일정에는 제목과 달력 배치 정보만 포함',()=>{const event={id:'event',date:'2026-09-23',title:'모임',time:'19:40',endTime:'21:00',location:'비공개 장소',description:'비공개 내용',unexpected:'secret'};assert.deepEqual(publicSeasonEvent(event),{id:'event',date:'2026-09-23',title:'모임'})});
test('일정 API는 비로그인 응답에서 상세 필드를 제거하고 로그인 시에만 반환',async()=>{
 const source=readFileSync(new URL('../app/api/hello-2027/schedule/route.ts',import.meta.url),'utf8');const js=ts.transpileModule(source.replace(/^import[\s\S]*?;\n/gm,''),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
 for(const authenticated of [false,true]){const exports={};const deps={NextResponse:{json:(body,options)=>({body,...options})},createClient:async()=>({auth:{getClaims:async()=>({data:{claims:authenticated?{sub:'member'}:null}})}}),publicSeasonEvent,getServiceClient:()=>({}),findAdminUserId:async()=>'owner',readSeasonEvents:async()=>[{id:'e',date:'2026-09-23',title:'모임',time:'19:40',location:'비밀 장소',description:'비밀 설명'}]};new Function('exports',...Object.keys(deps),js)(exports,...Object.values(deps));const response=await exports.GET();assert.equal(response.body.canViewDetails,authenticated);assert.equal(response.body.items[0].location,authenticated?'비밀 장소':undefined);assert.equal(response.headers['Cache-Control'],'private, no-store');}
});
