import assert from 'node:assert/strict';
import test from 'node:test';
import {personalGoalEditWindow,PERSONAL_GOAL_CHANGE_INTERVAL_MS} from '../lib/personal-goal-lock.ts';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
import {parseTimeMachineGoalInput,getTimeMachineTiming} from '../lib/time-machine-contract.ts';
const source=readFileSync(new URL('../app/api/me/time-machine/route.ts',import.meta.url),'utf8');
const js=ts.transpileModule(source.replace(/^import[\s\S]*?;\n/gm,''),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
function harness(auth=true,initial=null){
 const calls=[];let row=initial;
 class Response {constructor(body,status=200){this.body=body;this.status=status} static json(body,options={}){return new Response(body,options.status)}}
 const service={from(){let action='read',value;const filters=[];const query={select(){return query},eq(k,v){calls.push([k,v]);filters.push([k,v]);return query},lte(k,v){filters.push([k,v,'lte']);return query},insert(v){action='insert';value=v;calls.push({value:v});return query},update(v){action='update';value=v;calls.push({value:v});return query},async maybeSingle(){if(action==='insert'){if(row)return{error:{code:'23505'}};row={id:'goal',...value};return{data:row};}if(action==='update'){if(!row||!filters.every(([k,v,op])=>op==='lte'?row[k]<=v:row[k]===v))return{data:null};row={...row,...value};return{data:row};}return {data:row};}};return query}};
 const deps={NextResponse:Response,resolvePersonalMemberContext:async()=>auth?{ok:true,authUserId:'author',service,connection:{status:'approved',adminUserId:'operator',participant:{id:'member'}}}:{ok:false,reason:'unauthenticated'},guardReadRequest:()=>null,guardMutationRequest:()=>null,readLimitedJson:async req=>({ok:true,value:req.body}),logServerFailure:()=>{},isMissingTableError:()=>false,missingSchemaResponse:()=>({}),getTimeMachineTiming,parseTimeMachineGoalInput,TIME_MACHINE_SEASON_KEY:'4th',personalGoalEditWindow,PERSONAL_GOAL_CHANGE_INTERVAL_MS,invalidatePublicDashboardCache:()=>{},after:()=>{},broadcastDashboardRefreshFromServer:()=>{}};
 const exports={};new Function('exports',...Object.keys(deps),js)(exports,...Object.values(deps));return{...exports,calls};
}
test('목표 API는 비로그인 조회·저장을 DB 접근 전에 차단',async()=>{const h=harness(false);assert.equal((await h.GET({})).status,401);assert.equal((await h.POST({})).status,401);assert.deepEqual(h.calls,[])});
test('목표는 본인에게만 반환하며 저장 직후 30일 동안 수정 불가',async()=>{const h=harness();const saved=await h.POST({body:{goal_title:'꾸준히 달리기',auth_user_id:'victim'}});assert.equal(saved.status,201);assert.equal(saved.body.can_edit,false);assert.equal(h.calls.find(x=>x.value).value.auth_user_id,'author');assert.equal((await h.POST({body:{goal_title:'수정한 목표'}})).status,409);assert.equal((await h.GET({})).body.goal.title,'꾸준히 달리기');});
test('30일 이후 한 번만 원자적으로 변경하고 새 잠금 기간 시작',async()=>{const h=harness(true,{id:'goal',auth_user_id:'author',user_id:'operator',goal_title:'이전 목표',goal_detail:'',commitment:'',created_at:new Date(Date.now()-PERSONAL_GOAL_CHANGE_INTERVAL_MS-1).toISOString()});const results=await Promise.all([h.POST({body:{goal_title:'첫 변경'}}),h.POST({body:{goal_title:'두번째 변경'}})]);assert.equal(results.filter(x=>x.status===201).length,1);assert.equal(results.filter(x=>x.status===409).length,1);assert.equal((await h.GET({})).body.can_edit,false);assert.equal((await h.POST({body:{goal_title:'가'.repeat(81)}})).status,400);});
test('30일 경계 직전과 직후 판정',()=>{const created='2026-09-15T01:00:00Z',at=Date.parse(created)+PERSONAL_GOAL_CHANGE_INTERVAL_MS;assert.equal(personalGoalEditWindow(created,at-1).can_edit,false);assert.equal(personalGoalEditWindow(created,at).can_edit,true);});
test('관리자 목표 조회·삭제 API는 본문 없이 종료',async()=>{const admin=readFileSync(new URL('../app/api/admin/hello-2027/time-machine/route.ts',import.meta.url),'utf8').replace(/^import.*\n/gm,'');const exports={};new Function('exports','NextResponse',ts.transpileModule(admin,{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText)(exports,{json:(body,options)=>({body,...options})});for(const method of ['GET','DELETE']){const r=await exports[method]();assert.equal(r.status,410);assert.equal(r.body.goal,undefined)}});
