"use client";
import { useEffect, useState, type FormEvent } from "react";
import { SCHEDULE_START, SCHEDULE_END, type SeasonEvent } from "@/lib/season-schedule-contract";
const empty = { date: SCHEDULE_START, time: "", endTime: "", title: "", location: "", description: "" };
export function AdminSeasonSchedule() {
 const [items,setItems]=useState<SeasonEvent[]>([]), [draft,setDraft]=useState<Omit<SeasonEvent,"id">>(empty), [id,setId]=useState<string>(), [message,setMessage]=useState(""), [busy,setBusy]=useState(false), [loading,setLoading]=useState(true);
 const endpoint="/api/admin/hello-2027/schedule";
 async function load(){setLoading(true);try{const response=await fetch(endpoint,{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error);setItems(body.items);}catch(error){setMessage(error instanceof Error?error.message:"일정을 불러오지 못했어요.");}finally{setLoading(false);}}
 useEffect(()=>{void load(); const today=new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Seoul"}).format(new Date());setDraft({...empty,date:today<SCHEDULE_START?SCHEDULE_START:today>SCHEDULE_END?SCHEDULE_END:today});},[]);
 async function save(event:FormEvent){event.preventDefault();setBusy(true);setMessage("");try{const response=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...draft,...(id?{id}:{})})});const body=await response.json();if(!response.ok)throw new Error(body.error);setItems(previous=>[...previous.filter(item=>item.id!==body.item.id),body.item].sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)));setId(undefined);setDraft({...empty,date:draft.date});setMessage("저장했어요. 공개 달력을 새로고침하면 확인할 수 있어요.");}catch(error){setMessage(error instanceof Error?error.message:"저장하지 못했어요.");}finally{setBusy(false);}}
 async function remove(item:SeasonEvent){if(!window.confirm(`‘${item.title}’ 일정을 삭제할까요?`))return;setBusy(true);try{const response=await fetch(`${endpoint}?id=${item.id}`,{method:"DELETE"});const body=await response.json();if(!response.ok)throw new Error(body.error);setItems(old=>old.filter(row=>row.id!==item.id));if(id===item.id){setId(undefined);setDraft(empty);}setMessage("삭제했어요.");}catch(error){setMessage(error instanceof Error?error.message:"삭제하지 못했어요.");}finally{setBusy(false);}}
 return <section className="card p-5 sm:p-7"><h2 className="text-2xl font-bold">스내사 4기 일정</h2><p className="mt-2 text-sm text-slate-500">저장한 시간·장소·설명은 비로그인 관람객에게도 공개됩니다.</p><form onSubmit={save} className="my-6 grid gap-4"><fieldset disabled={busy} className="grid gap-4 disabled:opacity-60"><div className="grid grid-cols-2 gap-3"><label className="grid gap-2 text-sm">날짜<input required type="date" min={SCHEDULE_START} max={SCHEDULE_END} value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})} className="min-w-0 rounded-xl border border-slate-200 p-3"/></label><label className="grid gap-2 text-sm">시간 (선택)<input type="time" value={draft.time} onChange={e=>setDraft({...draft,time:e.target.value})} className="min-w-0 rounded-xl border border-slate-200 p-3"/></label><label className="grid gap-2 text-sm">종료 시간 (선택)<input aria-label="종료 시간 (선택)" type="time" value={draft.endTime||""} onChange={e=>setDraft({...draft,endTime:e.target.value})} className="min-w-0 rounded-xl border border-slate-200 p-3"/></label></div>{([['title','일정 제목',80],['location','장소 (선택)',120]] as const).map(([key,label,max])=><label key={key} className="grid gap-2 text-sm">{label}<input required={key==='title'} maxLength={max} value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})} className="rounded-xl border border-slate-200 p-3"/></label>)}<label className="grid gap-2 text-sm">설명 (선택)<textarea maxLength={4000} rows={3} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} className="rounded-xl border border-slate-200 p-3"/></label><button type="submit" className="btn-primary p-3">{busy?"처리 중…":id?"일정 수정":"일정 등록"}</button>{id&&<button type="button" onClick={()=>{setId(undefined);setDraft(empty);}}>수정 취소</button>}</fieldset></form><p role="status" className="my-4 text-sm text-blue-600">{message}</p>{loading?<p>일정을 불러오는 중…</p>:items.length===0?<p className="text-sm text-slate-500">등록된 일정이 없어요.</p>:items.map(item=><article key={item.id} className="my-3 flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-slate-50 p-4"><div><p className="text-xs text-slate-500">{item.date} {item.time}</p><h3 className="font-bold">{item.title}</h3></div><div className="flex gap-4 text-sm"><button disabled={busy} onClick={()=>{setId(item.id);setDraft({date:item.date,time:item.time,endTime:item.endTime||"",title:item.title,location:item.location,description:item.description});setMessage("");}}>수정</button><button disabled={busy} className="text-red-600" onClick={()=>void remove(item)}>삭제</button></div></article>)}</section>;
}
