"use client";
import { useEffect, useState } from "react";
import type { GiftRewardConfig } from "@/lib/gift-rewards";
export function AdminGiftRewards(){
 const [claims,setClaims]=useState<Array<{id:string;record_date:string;message:string;participant_id:string;participants:{name:string}|null}>>([]);
 const [claimsError,setClaimsError]=useState("");
 const [config,setConfig]=useState<GiftRewardConfig|null>(null);const [feedback,setFeedback]=useState("");const [busy,setBusy]=useState(false);
 useEffect(()=>{const controller=new AbortController();void fetch('/api/admin/hello-2027/gifts',{signal:controller.signal,cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setConfig(d.config);setClaims(d.claims||[]);setClaimsError(d.claimsError||"");}).catch(e=>{if(e.name!=="AbortError")setFeedback(e.message);});return()=>controller.abort();},[]);
 const total=config?.items.reduce((n,r)=>n+r.weight,0)??0;
 const patch=(id:string,change:object)=>setConfig(c=>c?{items:c.items.map(r=>r.id===id?{...r,...change}:r)}:c);
 const save=async()=>{if(!config||busy)return;setBusy(true);setFeedback("");try{const r=await fetch('/api/admin/hello-2027/gifts',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(config)});const d=await r.json();if(!r.ok)throw new Error(d.error);setConfig(d.config);setFeedback('저장했어요. 다음 추첨부터 적용됩니다.');}catch(e){setFeedback(e instanceof Error?e.message:'저장하지 못했어요.');}finally{setBusy(false);}};
 return <section className="space-y-4 rounded-3xl bg-white p-4 sm:p-6"><h2 className="text-xl font-bold">응원상자 보상 관리</h2><p className="text-sm leading-6 text-slate-600">문구와 상품별 확률을 설정하세요. 0%는 추첨 중지이며 전체 합계는 100%여야 해요. 기존 당첨 내역은 변경되지 않아요. 상품 쿠폰은 운영자가 확인 후 별도로 전달해주세요.</p>{feedback&&<p role="status" className="rounded-xl bg-blue-50 p-3">{feedback}</p>}{!config&&!feedback&&<p>설정을 불러오고 있어요.</p>}{config&&<><div className="flex flex-wrap items-center gap-3"><strong>합계 {(total/100).toFixed(2)}%</strong><span>응원 {(config.items.filter(r=>r.kind==='fortune').reduce((n,r)=>n+r.weight,0)/100).toFixed(2)}% · 상품 {(config.items.filter(r=>r.kind==='prize').reduce((n,r)=>n+r.weight,0)/100).toFixed(2)}%</span><button className="btn-primary" disabled={busy||total!==10000} onClick={()=>void save()}>{busy?'저장 중…':'설정 저장'}</button></div><div className="space-y-3">{config.items.map((r,i)=><fieldset key={r.id} disabled={busy} className="grid gap-3 rounded-2xl border border-slate-200 p-4 sm:grid-cols-[110px_1fr_100px]"><legend className="px-1 text-xs text-slate-500">보상 {i+1}</legend><label className="text-sm">종류<select className="mt-1 w-full rounded-lg border p-2" value={r.kind} onChange={e=>patch(r.id,{kind:e.target.value})}><option value="fortune">응원 문구</option><option value="prize">상품</option></select></label><label className="text-sm">문구 / 상품명<textarea className="mt-1 w-full rounded-lg border p-2" rows={2} maxLength={r.kind==='prize'?117:120} value={r.message} onChange={e=>patch(r.id,{message:e.target.value})}/></label><label className="text-sm">확률 (%)<input className="mt-1 w-full rounded-lg border p-2" type="number" min="0" max="100" step="0.01" value={r.weight/100} onChange={e=>patch(r.id,{weight:Math.round(Number(e.target.value)*100)})}/><button type="button" className="mt-2 text-xs underline" onClick={()=>setConfig(c=>c?{items:c.items.filter(x=>x.id!==r.id)}:c)}>목록에서 제거</button></label></fieldset>)}</div><button className="btn-secondary" disabled={busy||config.items.length>=80} onClick={()=>setConfig(c=>c?{items:[...c.items,{id:crypto.randomUUID(),kind:'prize',message:'새 상품',weight:0}]}:c)}>보상 추가</button><h3 className="pt-6 text-lg font-bold">최근 상품 당첨 내역 · 최대 100건</h3><p className="text-sm text-slate-600">쿠폰 전달 전 당첨 ID와 회원을 확인해주세요. 자동 쿠폰 발송·사용 처리는 제공하지 않습니다.</p>{claimsError&&<p role="alert">{claimsError}</p>}{!claims.length&&!claimsError&&<p>아직 상품 당첨 내역이 없어요.</p>}{claims.map(c=><article key={c.id} className="rounded-xl border p-3"><strong>{c.participants?.name||c.participant_id} · {c.message}</strong><p className="break-all text-xs text-slate-500">{c.record_date} · 당첨 ID {c.id}</p></article>)}</>}</section>;
}
