export const MAX_HELLO_2027_PROFILE_INTRODUCTIONS = 100;
export const MAX_PROFILE_INTRO_NAME_LENGTH = 40;
export const MAX_PROFILE_INTRO_TITLE_LENGTH = 40;
export const MAX_PROFILE_INTRO_LENGTH = 320;
